#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

# Gradle Toolchain
org.gradle.java.home=/Users/unchil/Library/Java/JavaVirtualMachines/jbr-21.0.11/Contents/Home
#org.gradle.java.home=/Users/unchil/Library/Java/JavaVirtualMachines/jbrsdk_jcef-21.0.11/Contents/Home
