// listOf("WS", "KR", "YK", "SU", "UJ")
@genName = WS

// inoutwater/getinoutwater
// YK UJ
###
GET {{host}}/{{ThermalWasteWater}}?serviceKey={{key}}&genName={{genName}}

###
GET {{host}}/{{WasteWater}}?serviceKey={{key}}&genName={{genName}}

