




GET http://192.168.35.107:7788/khoa/coastal_flooding_info/geojson_object?sido=경상북도&grade=F&type=select
Accept: application/json

###
### 서울 대기오염 정보 조회 로컬서비스
GET {{host}}/seoul/sdot_env_info
Accept: application/json



### 경기 대기오염 정보 조회 로컬서비스
GET {{host}}/gyonggi/sdot_env_info
Accept: application/json




### 서울/경기 대기오염 정보 조회 로컬서비스
GET {{host}}/sdot_env_info
Accept: application/json


###
GET {{host}}/khoa/coastal_flooding_info?page=1&size=10&grade=E&sido=전북특별자치도
Accept: application/json

###
GET {{host}}/khoa/tidal_current_info
Accept: application/json

###
GET {{host}}/khoa/observationinfo_current
Accept: application/json



###
GET {{host}}/khoa/observationinfo
Accept: application/json



###
GET {{host}}/khoa/waveinfo
Accept: application/json

###
GET {{host}}/khoa/sdot_env_info
Accept: application/json




###
GET {{host}}/{{seawaterinfo}}/oneDayBoxPlot



###
GET {{host}}/{{swi}}/mof_oneday


###
GET {{host}}/{{seawaterinfo}}/current



###
GET {{host}}/{{seawaterinfo}}/oneday


###
GET {{host}}/{{seawaterinfo}}/grid


###
GET {{host}}/{{stat}}


###
GET {{host}}/{{observatory}}


