
// space = %20
// : = %3A


###
@wtch_dt_start=20260905%20000000
@wtch_dt_end =20260906%20000000"
###
GET {{host}}/{{suburl}}
    ?ServiceKey={{key}}
    &_type=xml
    &numOfRows=100
    &pageNo=1
    &wtch_dt_start={{wtch_dt_start}}
    &wtch_dt_end={{wtch_dt_end}}

